name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1. Checkout 
      uses: actions/checkout@v3
    
    - name: 2. Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: 2.5 Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: 3. Build and push 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wantsomewalnut/hostservice:${{ github.sha }}
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repository: 'wsj0704/hostsvc-cd'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image: wantsomewalnut\/node-app:.*/images: dangtong\/node-app:${{ github.sha }}/g" hostservice-deploy.yaml
          git config --global user.email "dntjdwls0704@gmail.com"
          git config --global user.name "wsj0704"
          git commit -am "triggered by github action"
          git push origin main